In [1]:
#Create a 1D array with alias as np and perform the following methods
#1.np.zeros()
#2.np.ones()
#3.np.empty()
#4.np.arrange()
#5.np.reshape()
#6.np.linespace()

In [2]:
import numpy as np

In [3]:
first_numpy_array=np.array([1,2,3,4])

In [5]:
print(first_numpy_array)

[1 2 3 4]


In [6]:
array_with_zeros=np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
empty=np.empty((2,3))
empty

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [17]:
arange=np.arange(12)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
linspace=np.linspace(1,6,5)
linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [23]:
one_d_array=np.arange(15)
one_d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
two_d_array=one_d_array.reshape(3,5)  #1d array to 2d array

In [25]:
two_d_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
three_d_array=np.arange(27).reshape(3,3,3)  #1d array to 3d array

In [27]:
three_d_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])