In [1]:
import numpy as np

In [4]:
array_1d = np.array([1,2,3,4])
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
array_3d = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

In [5]:
print(array_1d)
print(array_2d)
print(array_3d)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [6]:
array_1d[1:]

array([2, 3, 4])

In [8]:
array_1d[3:6]

array([4])

In [11]:
array_1d[-3:-1]

array([2, 3])

In [16]:
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
array_2d[1,1:]


array([6, 7, 8])

In [28]:
array_3d[-2:-3:-1]

array([[3, 3, 3, 3]])