In [7]:
#arithematic operation using numpy of arrays

In [9]:
import numpy as np

In [10]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[9,7,6],[1,2,3]])

In [14]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[9 7 6]
 [1 2 3]]


In [15]:
np.add(a,b)

array([[10,  9,  9],
       [ 5,  7,  9]])

In [17]:
np.subtract(b,a)

array([[ 8,  5,  3],
       [-3, -3, -3]])

In [18]:
np.multiply(a,b)

array([[ 9, 14, 18],
       [ 4, 10, 18]])

In [19]:
np.divide(b,a)

array([[9.  , 3.5 , 2.  ],
       [0.25, 0.4 , 0.5 ]])

In [20]:
np.power(a,2) #square of values of matrix

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [21]:
np.power(a,b)

array([[  1, 128, 729],
       [  4,  25, 216]])