In [14]:
import numpy as np

In [21]:
from math import sin

In [22]:
a= 17
print(sqrt(a))

4.123105625617661


In [25]:
np_sqrt = np.sqrt([2,4,9,16])

In [26]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [27]:
from numpy import pi
np.cos(0)

1.0

In [28]:
np.sin(pi/2)

1.0

In [30]:
np.cos(pi)

-1.0

In [34]:
np.floor([1.4,1.5,6,7.5,4.6])

array([1., 1., 6., 7., 4.])

In [35]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])