In [1]:
############Part A
#array shapes and axis 0,1d,2d,3d etc

In [2]:
import numpy as np

In [3]:
np.array([24])  #zero d array

array([24])

In [4]:
np.array([1,2,3,4])#1d array

array([1, 2, 3, 4])

In [7]:
np.array([[1,2,3,4],[5,6,7,8]])#2d array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])#3d array

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [10]:
numpy_arr=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

In [12]:
numpy_arr.shape

(4, 4)

In [14]:
numpy_arr.ndim

2

In [15]:
#############Part B

In [17]:
import numpy as np

In [18]:
numpy_arr = np.array([x for x in range(1,10)])

In [19]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
numpy_arr = np.array([x for x in range(1,13)])

In [23]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
numpy_arr.reshape(2,2,-1)#calculates last dimention automatically

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
numpy_arr= numpy_arr.reshape(3,2,2)

In [28]:
numpy_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [29]:
#flattening to 1d from 3d
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])