In [1]:
#shape manipulation

In [3]:
import numpy as np

In [4]:
new_cyclist_trials=np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [5]:
new_cyclist_trials.ravel()  #flatten the dataset

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [7]:
new_cyclist_trials.reshape(3,4) #changes or reshapes the dataset to 3 rows and 4 columns

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [8]:
new_cyclist_trials.resize(2,6) #resize again to 2 rows and  6 columns

In [9]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [10]:
np.hsplit(new_cyclist_trials,2) #splits the array into two

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [11]:
new_cyclist_1=np.array([10,15,17,26,13,19])

In [12]:
new_cyclist_2=np.array([12,11,21,24,14,23])

In [15]:
np.hstack((new_cyclist_1,new_cyclist_2)) #stacks the array together

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])